### ISSUE TITLE
Member user info doesn't sync/merge with existing WP user info.

### ISSUE THREAD

**Issue by coreymckrill** [memberful/memberful-wp#143]
To replicate:

1. Create a new user in WordPress.
1. Create a new user in Memberful using _the same email address_.
1. Try to login to the WordPress site via the Memberful login form using that email address and the password from Memberful.
1. Result: Page redirects from the Memberful login overlay to the WordPress login form. No data is merged.

This might be an edge case, but here is how I think we would encounter it on the Theme Foundry site: we are considering installing a plugin called Postmatic that allows people to subscribe to new posts and comments via email, and respond to comments via email without having to go to the site. When someone subscribes, their email address becomes a new _Subscriber_-level user in the WordPress database (if they aren't in there already). They aren't sent login credentials because the idea is that they interact entirely via email. However, the problem would occur if a subscriber later went and bought one of our themes. Since their email address would already be in the WordPress database, it would collide with Memberful WP when it tries to create a new user to sync subscriptions/products to.

**Comment by dstrojny** [comment]
This is how Memberful works in that scenario @coreymckrill:

* Member attempts to sign in via Memberful: We ensure that user is already logged in to WordPress with the matching email or we make them log in with the matching email. Otherwise, someone could hijack an existing WordPress user account by signing up / signing in with Memberful using the same email address.
* If the member **is already logged into WordPress**, we automatically link the accounts and send them on their way as normal.

In the scenario you outlined, the member would have to log in with their existing WordPress account to link the two accounts together. If they were already logged in to our WordPress site as a subscriber, this would happen automatically.

The only area I see for improvement here would be adding a message about requiring you to log into WordPress to confirm the account. I thought we had something for this, but if we don't, we should open a separate ticket for that and close this one.

**Comment by coreymckrill** [comment]
Thanks for the clarification @dstrojny.

It sounds like this is an issue with the TTF specifically, then. Since Postmatic users won't know their login credentials, they won't be able to log in and link the accounts. And since we have basic authentication set up for everything on the wp-admin side, we wouldn't want people logging in like that anyway.

Another approach might be to see if we could automatically add new WP users to Memberful when they are created. But I will open a new ticket on the TTF site repo for that.

Feel free to close this.

**Comment by dstrojny** [comment]
Sounds good @coreymckrill. Thanks for letting me know.
