### ISSUE TITLE
Post list restricted label displays incorrectly

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#146]
Report with potential fix from a customer:

> With the `memberful_wp_add_protected_state_to_post_list` function, you are using a call "isset" to check if the post is restricted. However, I don't think that call works with ints - only with strings, so what I think happens is that it only returns true if the post ID happens to be the same number as one of the indices into the array. In my case my about page was ID 2 and the array contained 10 elements, so it labelled about as protected. However, a protected page, for example had ID 2900, so it returned false. I fixed it by using this instead at line 511: `if ( in_array($post->ID, $ids_of_protected_posts) ) {`

**Comment by FayeWilliams** [comment]
Additional info: isset appears to check if the index into the array is set (rather than whether the specific integer appears in the array). Instead of isset, use:
if (in_array($post->ID, $ids_of_protected_posts))
This will allow protected posts/pages to be correctly listed with "Protected by memberful".
