### ISSUE TITLE
Conditional Sign In Menu Item Still dispalys to logged in users

### ISSUE THREAD

**Issue by ChaseWPDEV** [memberful/memberful-wp#315]
Plugin provided "Sign In" conditional menu item still appears for logged-in users.

**Comment by mrhead** [comment]
@ChaseWPDEV I presume this happens in a block theme with the navigation block. Is that right?

At the moment, it's not possible to filter menu items in the navigation block:
- https://core.trac.wordpress.org/ticket/54684
- https://github.com/WordPress/gutenberg/pull/37998

We plan to fix this in our plugin once this is fixed in WordPress.

Internal to-do: https://3.basecamp.com/3293071/buckets/9856127/todos/4716127696

If this issue is not related to the new navigation block, please reopen it with more details. Thanks!
