### ISSUE TITLE
This plugin has been closed as of November 24, 2022 and is not available for download. This closure is temporary, pending a full review.

### ISSUE THREAD

**Issue by maciejmackowiak** [memberful/memberful-wp#336]
Any info why the plugin is closed here:
https://wordpress.org/plugins/memberful-wp/

**Comment by archon810** [comment]
I pinged the team here https://wordpress.slack.com/archives/C1LBM36LC/p1670535837847809. Hope it's back soon.

**Comment by mrhead** [comment]
We are sorry for any caused inconveniences.

WordPress closed our plugin because one of the emails associated with the plugin stopped working. When WordPress noticed it, they blocked our plugin.

This is only temporary, and we are working with them on re-enabling the plugin. However, every closed plugin needs to be fully audited, so this is taking some time.

**Comment by mrhead** [comment]
In the meantime, if you need to install our plugin, you can download it on the following URL and then upload it to your WordPress site:

https://github.com/memberful/memberful-wp/releases/tag/v1.70.1

**Comment by mrhead** [comment]
We are back! 🎉

https://wordpress.org/plugins/memberful-wp/

**Comment by archon810** [comment]
Can you please comment on the security fixes that the change log mentions now?
